name: Deploy

on:
  release:
    types: [published]

deploy:
  needs: [test_build]

env:
  LOGIN: ${{ secrets.DOCKER_LOGIN }}
  NAME: ${{ secrets.DOCKER_NAME }}

jobs:
  deploy:
    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PSW }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@main
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .